api/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from rest_framework.urlpatterns import format_suffix_patterns
from .views import ArticlesView
from smarturls import surl
from . import views

app_name = 'api'

urlpatterns = {
    surl('/', views.index_API, name='index_API'),
    surl('articles/(?P<entities>.+)/$', ArticlesView.as_view()),

}

# Adiciona os sufixos de URL aceitos aos nossos urlpatterns.
# Por padrão adiciona html e json.
urlpatterns = format_suffix_patterns(urlpatterns)

dashboard/urls.py
from django.conf.urls import url
from smarturls import surl


from django.contrib.auth import views as auth_views
from . import views

app_name = 'dashboard'
urlpatterns = [
    surl('/', views.index, name='index'),
    surl('login/', auth_views.login, name='login'),
    surl('logout/', auth_views.logout, {'next_page': '/'}, name='logout'),
    surl('signup/', views.signup, name='signup'),
    surl('about/', views.about, name='about'),
    surl('services/', views.services, name='services'),
    surl('contact/', views.contact, name='contact'),
    #url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^password_reset/$', views.password_reset, {'post_reset_redirect' : 'dashboard:index'},name="password_reset"),
    url(r'^confirmation/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activationview, name='activation'),
    ]

django_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from smarturls import surl
from django.contrib.auth import views as auth_views
import api

urlpatterns = [
    url(r'^auth/', include('rest_framework.urls',
        namespace='rest_framework')),
    surl('', include('dashboard.urls')),
    surl('search/', include('search.urls')),
    surl('admin/', admin.site.urls),
    surl('api/', include('api.urls')),
    url('^', include('django.contrib.auth.urls')),
]

search/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from smarturls import surl
import api

from . import views

app_name = 'search'

urlpatterns = [
    surl('/', views.index, name='index'),
    surl('history/', views.history, name='history'),
    surl('download/', views.download, name='download'),
    surl('config/', views.configuration, name='config'),
    surl('create_keyword/', views.create_keyword, name='create_keyword'),
    surl('create_ignored/', views.create_ignored, name='create_ignored'),
    surl('delete_keyword/', views.delete_keyword, name='delete_keyword'),
    surl('delete_ignored/', views.delete_ignored, name='delete_ignored'),

]

search/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django import utils
from django.utils.encoding import python_2_unicode_compatible
from django.core.validators import MinLengthValidator
from django.core.exceptions import ValidationError
import json

### MONGO
import mongoengine as mg
from django_project.settings import MONGO_DATABASE

mg.connect(
    db=         MONGO_DATABASE['db'],
    username=   MONGO_DATABASE['username'],
    password=   MONGO_DATABASE['password'],
    host=       MONGO_DATABASE['host'],
)


@python_2_unicode_compatible
class Article(mg.Document):
    url = mg.StringField(max_length=200, required=True, validators=[MinLengthValidator(1)])
    title = mg.StringField(max_length=200, required=True, validators=[MinLengthValidator(1)])
    short_summary = mg.StringField(max_length=200, required=True, validators=[MinLengthValidator(1)])
    long_summary = mg.StringField(max_length=500, required=True, validators=[MinLengthValidator(1)])
    publish_date = mg.DateTimeField()
    risk = mg.IntField()
    entities = mg.ListField()
    category = mg.StringField(max_length=20)
    def __str__(self):
        return "URL: {0}\n".format(self.url)

    def fill_and_create(self, article, entities, risk, category):
        if article.title != "" and article.summary != "" and article.url != "":
            self.url=article.url
            self.short_summary=article.summary[:200]
            self.long_summary=article.summary
            self.title=article.title
            self.entities= entities
            self.publish_date= article.publish_date
            self.risk = risk
            self.category = category
            self.save()
            return self
        else:
            return None


@python_2_unicode_compatible  # only if you need to support Python 2
class Query(models.Model):
    name = models.CharField(max_length=200, blank=False)
    time = models.DateTimeField('date searched', default=utils.timezone.now)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
     # JSON-serialized (text) version of the list
    entities = models.TextField(null=True)
    engines = models.TextField(null=True)
    def __str__(self):
        return "User: {0}, Name: {1}, Time: {2}, Entities: {3}, Engines: {4}".format(str(self.user), self.name, str(self.time), str(self.entities), str(self.engines))

    def get_engines(self):
        return self.get('engines')

    def get_entities_formated(self):
        return ",".join(self.get('entities'))

    def get(self, field):
        return json.JSONDecoder().decode(getattr(self, field))

    def get_engines_formated(self):
        return ", ".join(self.get('engines'))

    def set(self, field, list):
        setattr(self, field, json.dumps(list))

@python_2_unicode_compatible
class Keyword(models.Model):
    name = models.CharField(max_length=100, blank=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return "Name: {0}, User{1}".format(self.name,self.user)

@python_2_unicode_compatible
class IgnoredDomain(models.Model):
    name = models.CharField(max_length=100, blank=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return "Name: {0}, User{1}".format(self.name,self.user)

search/forms.py
# -*- coding: utf-8 -*-
from django import forms
from search.models import *

class SearchForm(forms.Form):
    ENGINES = (
        ('google', 'Google'),
        ('yahoo', 'Yahoo'),
        ('bing', 'Bing'),
    )
    query = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'style':'font-size:15px', 'size': 35, 'placeholder': 'Digite sua busca, separada por vírgulas.'}))
    engines = forms.MultipleChoiceField(label="Selecione pelo menos 1", choices=ENGINES,
            required=True, error_messages={'required': 'Por favor, preenche pelo menos uma fonte de buscas'},
            widget=forms.CheckboxSelectMultiple(), initial=('google',))
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(SearchForm, self).__init__(*args, **kwargs)
        self.fields['keywords'] = forms.MultipleChoiceField(required=False,
            choices=[ (o.name, str(o.name)) for o in Keyword.objects.filter(user=user)],
            widget=forms.CheckboxSelectMultiple(),
            )

class KeywordForm(forms.ModelForm):
    name = forms.CharField(max_length=100, required=True, label="Palavra-chave:")
    class Meta:
        model = Keyword
        fields = ['name']


class IgnoredDomainForm(forms.ModelForm):
    name = forms.CharField(max_length=100, required=True, label="Domínio para excluir da busca:")
    class Meta:
        model = IgnoredDomain
        fields = ['name']

search/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from news_scrapper.search_urls import get_urls
from news_scrapper.url_parser import get_articles
from django.views import generic, View
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from forms import *
from models import Article, Query, Keyword
import time, sys, json
from reportlab.pdfgen import canvas
from io import BytesIO
from time import gmtime, strftime


from datascience.news_classifier import NewsClassifier


from django.core.files.storage import FileSystemStorage

from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from urlparse import urlparse




def save_articles(articles, entities):
    saved_articles = []
    for art in articles:
        predictions = NewsClassifier().news_predictions(art.summary)
        saved_article = Article().fill_and_create(art, entities, predictions['risk'], predictions['category'])
        if saved_article is not None:
            print "SAVED AN ARTICLE: {0}".format(saved_article).encode('utf-8')
            sys.stdout.flush()
            saved_articles.append(saved_article)
    return saved_articles

def check_articles_db(urls, entities):
    urls_not_in_db = []
    articles_to_display = []
    for url in urls:
        article_in_db = Article.objects.filter(url=url).first()
        if article_in_db is None:
            urls_not_in_db.append(url)
        else:
            article_in_db.entities = list(set(article_in_db.entities).union(set(entities))) # update the Article's entities
            article_in_db.save()
            articles_to_display.append(article_in_db)
    return [articles_to_display, urls_not_in_db]


def get_domain(url):
    return urlparse(url).netloc

def calculate_risk(entities):
    risk = {}
    for entity in entities:
        articles = [art for art in Article.objects.all() if entity in art.entities]
        l=[art.risk for art in articles if art.risk != None]
        if len(l)>0:
            risk[entity] = float(sum(l))/len(l)
        else:
            risk[entity] = 1
    return risk


@login_required
def index(request):
    form = SearchForm(user=request.user)
    context = {'form': form}

    if request.method == 'GET':
        start = time.time()
        page = int(request.GET.get('page',1)) # Gets the page number or 1 if it does not exist in the GET dict
        context['page'] = page
        form = SearchForm(request.GET,user=request.user)
        if form.is_valid():
            entities = [e.strip(' ').lower() for e in form.cleaned_data['query'].split(',')] # Split and clean query
            search_engines = form.cleaned_data['engines']
            keywords = form.cleaned_data['keywords']
            search_keys = entities + keywords

            print page
            urls = get_urls(search_keys, search_engines, range(page-1,page))

            ignored_domains = [ign.name for ign in request.user.ignoreddomain_set.all()]                 # Gets all IgnoredDomains from User
            urls = [url for url in urls if get_domain(url) not in ignored_domains] # Gets the non-ignored URLs

            [articles_to_display, urls_not_in_db] = check_articles_db(urls, entities)   # checks the URLs from the search, and returns the Articles
                                                                                        # already stored, as well as the URLs th(at are not stored

            articles_from_search = get_articles(urls_not_in_db)             # downloads "Newspaper Articles" from the URLs given
            saved_articles = save_articles(articles_from_search, entities)  # saves the "Newspaper Articles" into "Django Articles" and returns them
            context['risks'] = calculate_risk(entities)
            for entity in entities:
                context['risks'][entity] = int(100*(context['risks'][entity]-1)/2) # Format to percent

            if saved_articles:
                articles_to_display += saved_articles                       # show the just saved Articles

            if 'dont_save_query' not in request.GET:
                query = Query.objects.create(name="Pesquisa sobre {0}".format(entities), user=request.user, entities=json.dumps(entities), engines=json.dumps(search_engines))
            articles_to_display = [art for art in articles_to_display if art.category != "Positiva"]
            context['articles'] = articles_to_display
            context['urls'] = urls
            categories_dict = {}
            for art in articles_to_display:
                if art.category not in categories_dict.keys():
                    categories_dict[art.category] = 1
                else:
                    categories_dict[art.category] += 1
            context['categories'] = categories_dict
            loadingpagetime = time.time() - start
            print "LOADING PAGE TIME: {0}".format(loadingpagetime)
        else:
            print "-----FORMULARIO INVALIDO------"

    return render(request, 'search/index.html', context)



@login_required
def history(request):
    context = {'queries':request.user.query_set.all()}
    return render(request, 'search/history.html', context)


@login_required
def download(request):
    #form = ReportForm()
    #context = {'form': form}
    if request.method == 'GET':
        urls = request.GET.getlist("article_url")
        #form = ReportForm(request.GET.getlist("article_url[]"))
        time = strftime("%Y-%m-%d-%H_%M_%S", gmtime())
        doc = SimpleDocTemplate("/tmp/relatorioNOTICIAS%s.pdf" %time)
        styles = getSampleStyleSheet()
        Story = [Spacer(1,0*inch)]
        style = styles["Normal"]
        bogustext = ("Relatório de notícias:")
        p = Paragraph(bogustext, style)
        Story.append(p)
        Story.append(Spacer(1,0.2*inch))
        for i, url in enumerate(urls):
            article_in_db = Article.objects.filter(url=str(url)).first()
            if article_in_db is not None:
                bogustext = ("%d. Título da notícia: %s." % (i+1, article_in_db.title))
                p = Paragraph(bogustext, style)
                Story.append(p)
                bogustext = ("Resumo da notícia: %s." % article_in_db.long_summary)
                p = Paragraph(bogustext, style)
                Story.append(p)
                if article_in_db.publish_date != None:
                    bogustext = ("Data de publicação: %s." % article_in_db.publish_date)
                    p = Paragraph(bogustext, style)
                    Story.append(p)
                if article_in_db.risk == 1:
                    bogustext = "Risco dessa notícia: Baixo."
                    p = Paragraph(bogustext, style)
                    Story.append(p)
                elif article_in_db.risk == 2:
                    bogustext = "Risco dessa notícia: Médio."
                    p = Paragraph(bogustext, style)
                    Story.append(p)
                elif article_in_db.risk == 3:
                    bogustext = "Risco dessa notícia: Alto."
                    p = Paragraph(bogustext, style)
                    Story.append(p)
                bogustext = "Entidades envolvidas na notícia: "
                for entity in article_in_db.entities:
                    bogustext += ("%s " %entity)
                p = Paragraph(bogustext, style)
                Story.append(p)
                bogustext = ("Categoria da notícia: %s." % article_in_db.category)
                p = Paragraph(bogustext, style)
                Story.append(p)
                bogustext = ("Fonte da notícia: %s" % get_domain(url))
                p = Paragraph(bogustext, style)
                Story.append(p)
                bogustext = ("Url da notícia: %s" % url)
                p = Paragraph(bogustext, style)
                Story.append(p)
                Story.append(Spacer(1,0.2*inch))

        doc.build(Story)
        fs = FileSystemStorage("/tmp")
        with fs.open("relatorioNOTICIAS%s.pdf" %time) as pdf:
            response = HttpResponse(pdf, content_type='application/pdf')
            response['Content-Disposition'] = ('attachment; filename="relatorioNOTICIAS%s.pdf"' %time)
            return response

    return response


@login_required
def configuration(request):
    context = {
        'keyword_form':KeywordForm(),
        'ignored_form':IgnoredDomainForm(),
        'keywords':request.user.keyword_set.all(),
        'ignored_domains':request.user.ignoreddomain_set.all(),
        }
    return render(request, 'search/configuration.html', context)


@login_required
def create_keyword(request):
    if request.method == "POST":
        form = KeywordForm(request.POST)
        if form.is_valid():
            form.instance.name = form.instance.name.lower()
            form.instance.user = request.user
            print form.save()
    return redirect(reverse('search:config'))

@login_required
def create_ignored(request):
    if request.method == "POST":
        form = IgnoredDomainForm(request.POST)
        if form.is_valid():
            form.instance.name = form.instance.name.lower()
            form.instance.user = request.user
            print form.save()
    return redirect(reverse('search:config'))

@login_required
def delete_keyword(request):
    if request.method == "POST":
        keyword_id = request.POST['keyword_id']
        Keyword.objects.get(pk=keyword_id).delete()
    return redirect(reverse('search:config'))

@login_required
def delete_ignored(request):
    if request.method == "POST":
        ignored_id = request.POST['ignored_id']
        IgnoredDomain.objects.get(pk=ignored_id).delete()
    return redirect(reverse('search:config'))

search/templates/search/base.html
{# Load the tag library #}
{% load bootstrap3 %}
{% load static %}


{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}


<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'dashboard/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'dashboard/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="{% static 'dashboard/vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="{% static 'dashboard/css/search.css' %}" rel="stylesheet">

   <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
   <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
   <!--[if lt IE 9]>
       <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
       <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
   <![endif]-->
<title>Novo Caminho</title>
<link rel="shortcut icon" type="image/png" href="{% static "images/favicon.png" %}">
</head>

<body>
    <div id="wrapper" class="active">
        <!-- Sidebar -->
                <!-- Sidebar -->
           <div id="sidebar-wrapper">
             <ul id="sidebar_menu" class="sidebar-nav">
                <li class="sidebar-brand" id="menu-toggle">
                    <img id="main_icon" src="{% static "/images/favicon.png" %}"></img>
                </li>
             </ul>
             <ul id="sidebar" class="sidebar-nav">
               <li><a href="{% url 'search:index' %}">Pesquisa<span class="sub_icon glyphicon glyphicon-search"></span></a></li>
               <li><a href="{% url 'search:history' %}">Histórico<span class="sub_icon glyphicon glyphicon-folder-open"></span></a></li>
               <li><a href="{% url 'search:config' %}">Opções<span class="sub_icon glyphicon glyphicon-cog"></span></a></li>
             </ul>
          </div>

          <!-- Page content -->
          <div id="page-content-wrapper">
            <!-- Keep all page content within the page-content inset div! -->
            <div class="page-content inset">

{% block content %}
{% endblock %}
</div>

</div>


    <!-- jQuery -->
    <script src="{% static 'dashboard/vendor/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'dashboard/vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="{% static 'dashboard/vendor/scrollreveal/scrollreveal.min.js' %}"></script>
    <script src="{% static 'dashboard/vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

    <!-- Theme JavaScript -->
    <script src="{% static 'dashboard/js/search.js' %}"></script>


</body>
</html>

search/templates/search/configuration.html
{% extends "search/base.html" %}

{% block content %}
<div class="row" id="titulo">
<center><p> Página de Configuração </p></center>
</div>
<hr>
<div class="row">
    <div class="col-xs-12">
          <form method="post" action="{% url 'search:create_keyword'%}">
            {% csrf_token %}
            <p> Adicione palavras-chave: {{ keyword_form.name }}
            <button type="submit" class="page-scroll btn btn-default btn-xl sr-button">Adicionar</button>
            </p>
          </form>
  </div>
</div>
<div class="row">
    <div class="col-xs-12">
          {% for keyword in keywords %}
            <form method="post" action="{% url 'search:delete_keyword'%}">
              {% csrf_token %}
              <input type="hidden" name="keyword_id" value={{keyword.id}}>

              <div style="float:left" class="badge progress-bar-info">
                {{keyword.name|upper}}
                <br>
                <button type="submit" class="close">&times;</button>

              </div>

            </form>
          {% endfor %}
    </div>
</div>


<hr style="height:1px;border:none;background-color:#bfbfbf;width:93%">

<div class="row">
    <div class="col-xs-12">
          <form method="post" action="{% url 'search:create_ignored'%}">
            {% csrf_token %}
            <p> Domínios de exceção: {{ ignored_form.name }}
            <button type="submit" class="page-scroll btn btn-default btn-xl sr-button">Adicionar</button>
            </p>
          </form>

        {% for ignored_domain in ignored_domains %}
          <form method="post" action="{% url 'search:delete_ignored'%}">
            {% csrf_token %}
            <input type="hidden" name="ignored_id" value={{ignored_domain.id}}>

            <div style="float:left" class="badge progress-bar-info">
              {{ignored_domain.name}}
              <br>
              <button type="submit" class="close">&times;</button>
            </div>
          </form>
         {% endfor %}

  </div>
</div>

{% endblock %}

search/templates/search/history.html
{% extends "search/base.html" %}

{% block content %}
<div id="titulo">
<center><p> Histórico de Pesquisas </p></center>
</div>
<hr>
<ol>
  {% for query in queries %}
  <center>
    <li style="color:green"> Você pesquisou: {{query.get_entities_formated}}
    <br>
    Na data: {{query.time}} | No(s) site(s): {{query.get_engines_formated}}
    </li>
    <br>
    <form method="get" action={% url 'search:index' %}>
      {% for engine in query.get_engines %}
        <input type="hidden" name="engines" value="{{engine}}">
      {% endfor %}
      <input type="hidden" name="query" value="{{query.get_entities_formated}}">
      <input type="hidden" name="dont_save_query" value="1">
      <button type="submit" class="page-scroll btn btn-default btn-xl sr-button"> Refaça a busca!</button>
    </form>
  </center>
<hr style="height:1px;border:none;background-color:#bfbfbf;width:93%">
  {% endfor %}
</ol>
{% endblock %}

search/templates/search/index.html
{% extends "search/base.html" %}
{% load bootstrap3 %}
{% load static %}
{% load search_extras %}
{% block content %}


  <div class="row">

      <span class="dropdown" id="logoutANDname">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user.get_username }} <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><center><a href="{% url 'dashboard:password_reset' %}">Trocar senha</a></center></li>
          <li role="separator" class="divider"></li>
          <li><center><a href="{% url 'dashboard:logout' %}">{% bootstrap_button content='Logout'%}</a></center></li>
        </ul>
      </span>

  <form method="get" style="background-color:#e2e2e2" class="well">
      {{form.query}}
      <input type="submit" value="Pesquisar" class="btn btn-primary btn-xl page-scroll">

   </div>
      <!-- End first ROW -->

      <!-- Start the second ROW -->
   <div class="row">
        <div class="col-xs-7"><!-- div da esquerda -->
            <br>
            <ol>
            {% for article in articles %}
              <li><a style:"font-size:1" href="{{article.url}}">{{article.title}}</a></li>
              {{article.short_summary}}...
              <p style="color:green">{{article.url|urlizetrunc:30}} {% if article.publish_date is not None %}| Publicada em: {{article.publish_date}}{% endif %} </p>
              <hr>
            {% endfor %}
            </ol>

            {% if articles %}
            <center>
            <ul class="pagination">
              {% if page > 1 %}
                <li><a href="{% goto_page page|add:"-1" %}">Anterior</a></li>
              {% endif %}
              <li class="active"><a href="{% goto_page page %}">{{page}}</a></li>
              <li><a href="{% goto_page page|add:"1" %}">{{page|add:"1"}}</a></li>
              <li><a href="{% goto_page page|add:"2" %}">{{page|add:"2"}}</a></li>
              <li><a href="{% goto_page page|add:"3" %}">{{page|add:"3"}}</a></li>
            </ul>
            </center>
            {% endif %}
        </div>

        <div class="col-xs-5" style="border-left:3px solid #e2e2e2;height:1430px"> <!-- div da direita -->
          <div class="row">
            <br>
            <br>
            <div class="row">
                <div id="engines">
                    <p> Selecione pelo menos 1 site: </p>
                  {{form.engines}}
                </div>
                <div id="keywords">
                    <p> Escolha as palavras-chave: </p>
                  {{form.keywords}}
                </div>
		<div id="categories">
            <p> Número de notícias por categoria </p>
		      {% for category,count in categories.iteritems %}
			  <div class="badge">
			    <span style="vertical-align:-webkit-baseline-middle">{{category}}<span class="badge">{{count}}</span></span>
			  </div>
		      {% endfor %}
		</div>
            </div>
	    </form>
          </div>
            <div class="row" id="risk_bar">
                {% if articles %}
                <center><form method="get" action= {% url 'search:download' %}>
                     {% for url in urls %}
                        <input type="hidden" name="article_url" value="{{url}}">
                     {% endfor %}
                     <button type="submit" class="page-scroll btn btn-default btn-xl sr-button"> Gerar Relatório</button>
                </form></center>
                {% endif %}
              {% if risks %}
              <h2>Risco:</h2>
              {% endif %}
              {% for entity, risk in risks.iteritems %}

              <div class="container">
                  <div class="row">
                      <div class="col-md-6">
                          <div class="progress">
                              <div class="progress-bar" style="width:{{risk}}%; background:#49719b;">
                                  <span class="progress-title">{{entity}}</span>
                                  <div class="progress-value">{{risk}}%</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              {% endfor %}
              </div>
            </div>
        </div>
   </div>



  {% if error_message %}
  <div class="alert alert-danger" role="alert">
      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
      <span class="sr-only">Error:</span>
      {{ error_message }}
    </div>
  {% endif %}

{% endblock %}