api/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from rest_framework.urlpatterns import format_suffix_patterns
from .views import ArticlesView
from smarturls import surl
from . import views

app_name = 'api'

urlpatterns = {
    surl('/', views.index_API, name='index_API'),
    surl('articles/(?P<entities>.+)/$', ArticlesView.as_view()),

}

# Adiciona os sufixos de URL aceitos aos nossos urlpatterns.
# Por padrão adiciona html e json.
urlpatterns = format_suffix_patterns(urlpatterns)

dashboard/urls.py
from django.conf.urls import url
from smarturls import surl


from django.contrib.auth import views as auth_views
from . import views

app_name = 'dashboard'
urlpatterns = [
    surl('/', views.index, name='index'),
    surl('login/', auth_views.login, name='login'),
    surl('logout/', auth_views.logout, {'next_page': '/'}, name='logout'),
    surl('signup/', views.signup, name='signup'),
    surl('about/', views.about, name='about'),
    surl('services/', views.services, name='services'),
    surl('contact/', views.contact, name='contact'),
    #url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^password_reset/$', views.password_reset, {'post_reset_redirect' : 'dashboard:index'},name="password_reset"),
    url(r'^confirmation/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activationview, name='activation'),
    ]

django_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from smarturls import surl
from django.contrib.auth import views as auth_views
import api

urlpatterns = [
    url(r'^auth/', include('rest_framework.urls',
        namespace='rest_framework')),
    surl('', include('dashboard.urls')),
    surl('search/', include('search.urls')),
    surl('admin/', admin.site.urls),
    surl('api/', include('api.urls')),
    url('^', include('django.contrib.auth.urls')),
]

dashboard/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import Group
# Create your models here.

verified, created = Group.objects.get_or_create(name='verified')

dashboard/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=20, required=False,
            widget=forms.TextInput(attrs={'maxlength':5, 'placeholder': 'Primeiro nome'}))
    last_name = forms.CharField(max_length=20, required=False,
            widget=forms.TextInput(attrs={'maxlength':5, 'placeholder': 'Segundo nome'}))
    email = forms.EmailField(max_length=254,
            widget=forms.TextInput(attrs={'maxlength':5, 'placeholder': 'E-mail'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

#widget=forms.TextInput(
#    attrs={'size': 5, 'class': 'form-control', 'placeholder': 'First Name'})

from django.contrib.auth.forms import PasswordResetForm
from django.core.mail import EmailMultiAlternatives
from django.template import loader

class CustomPasswordResetForm(PasswordResetForm):
    """
        Overriding the Email Password Resert Forms Save to be able to send HTML email
    """
    def send_mail(self, subject_template_name, email_template_name,
                  context, from_email, to_email, html_email_template_name=None):
        """
            Sends a django.core.mail.EmailMultiAlternatives to 'to_email'.
        """
        subject = loader.render_to_string(subject_template_name, context)
        # Email subject *must not* contain newlines
        subject = ''.join(subject.splitlines())
        body = loader.render_to_string(email_template_name, context)

        email_message = EmailMultiAlternatives(subject, body, from_email, [to_email])
        # New line introduce
        email_message.attach_alternative(body, 'text/html')

        if html_email_template_name is not None:
            html_email = loader.render_to_string(html_email_template_name, context)
            email_message.attach_alternative(html_email, 'text/html')

        email_message.send()

dashboard/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from forms import SignUpForm
from django.contrib.auth.views import password_reset as django_password_reset
from dashboard.forms import CustomPasswordResetForm
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.core.mail import EmailMultiAlternatives
from django.http import HttpResponseRedirect

# Create your views here.

def index(request):
    reset_password = False
    ## GAMBIARRA
    domain = request.META['HTTP_HOST']
    referrer = str(HttpResponseRedirect(request.META.get('HTTP_REFERER'))).split("http://", 1)
    if len(referrer)>1:
        if (domain+"/password_reset/") in referrer[1]:
            reset_password = True
    ## END GAMBIARRA
    if request.user.is_authenticated:
        return redirect(reverse('search:index'))
    return render(request, 'dashboard/index.html', {'reset_password':reset_password})

def about(request):
    return render(request, 'dashboard/about.html')

def services(request):
    return render(request, 'dashboard/services.html')

def contact(request):
    return render(request, 'dashboard/contact.html')


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            domain = request.META['HTTP_HOST']
            confirmation_email(domain, form.cleaned_data.get('email'), user)
            return redirect(reverse('search:index'))
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})

def password_reset(*args, **kwargs):
    """
        Overriding the Email Password Resert Forms Save to be able to send HTML email
    """
    kwargs['password_reset_form'] = CustomPasswordResetForm
    return django_password_reset(*args, **kwargs)

def confirmation_email(domain, email, new_user):
    to = email
    token = default_token_generator.make_token(new_user)
    uid = urlsafe_base64_encode(force_bytes(new_user.pk))
    html_content = """<h3>Bem vindo %s </h3><p>Para confirmar seu registro no Novo Caminho clique no link abaixo:
    <a href='http://%s/confirmation/%s/%s'>Confirmação</a><br><p><b>Obrigado por se inscrever em nossos serviços.</b></p><br>
    <p>Aproveite!</p><small>Mensagem automática. Por favor no responda.</small>"""%(new_user.username, domain, uid, token)
    msg = EmailMultiAlternatives("Confirmação de email Novo Caminho", html_content, 'novocaminhocodenation@gmail.com', [to])
    msg.attach_alternative(html_content, 'text/html') #Definimos el contenido como html
    msg.send()

def activationview(request, uidb64, token):
    print (uidb64, token)
    if uidb64 is not None and token is not None:
        from django.utils.http import urlsafe_base64_decode
        from django.utils.encoding import force_text
        uid = urlsafe_base64_decode(uidb64)

        from django.contrib.auth import get_user_model
        user_model = get_user_model()
        user = user_model.objects.get(pk=uid)

        if user is not None and default_token_generator.check_token(user, token):
            print("ENTROU NO IF")
            from django.contrib.auth.models import Group
            g = Group.objects.get(name='verified')
            g.user_set.add(user)
            return redirect('search:index')

    return redirect('login')

dashboard/templates/dashboard/about.html
{% extends 'registration/base.html' %}
{% load bootstrap3 %}
{% load static %}
{% block title %}About{% endblock %}

{% block content %}

<body style="background-color:#c3c3c3;">

<section id="services">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">Estudantes da Code:Nation</h2>
                <hr class="primary">
            </div>
        </div>
    </div>
    <br>
    <br>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-6 text-center">
                <div class="service-box">
                    <img src="{% static "images/felipe2.jpg" %}"  class="sr-icons img-circle" width="125" height="125">
                    <h3>Luis Felipe Pelison</h3>
                    <p class="text-muted">Atualmente na 7a fase de Engenharia de Controle e Automação na UFSC.</p>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 text-center">
                <div class="service-box">
                    <img src="{% static "images/pedro2.jpg" %}"  class="sr-icons img-circle" width="125" height="125">
                    <h3>Pedro Fornari</h3>
                    <p class="text-muted">Formando em Engenharia Eletrônica na UFSC.</p>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 text-center">
                <div class="service-box">
                    <img src="{% static "images/henke.jpg" %}"  class="sr-icons img-circle" width="125" height="125">
                    <h3>Eduardo Henke</h3>
                    <p class="text-muted">Atualmente na 3a fase de Engenharia de Controle e Automação na UFSC.</p>
                </div>
            </div>
        </div>
    </div>
</section>

</body>

{% endblock %}

dashboard/templates/dashboard/contact.html
{% extends 'registration/base.html' %}
{% load bootstrap3 %}
{% load static %}
{% block title %} Contact {% endblock %}

{% block content %}

<body style="background-color:#f5e254;">
<br>
<br>
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">Entre em contato, adoramos conversar!</h2>
                <hr class="primary">
                <p>Dúvidas? Sugestões? Críticas? Entre em contato conosco o mais rápido possível!</p>
                <p>Adoraremos ouvir você. :)</p>
            </div>
            <br>
            <div class="col-lg-4 col-lg-offset-2 text-center">
                <i class="fa fa-phone fa-3x sr-contact"></i>
                <p>+55 (48) 12345-6789</p>
            </div>
            <div class="col-lg-4 text-center">
                <i class="fa fa-envelope-o fa-3x sr-contact"></i>
                <p><a href="mailto:novocaminhocodenation@gmail.com">novocaminhocodenation@gmail.com	</a></p>
            </div>
        </div>
    </div>
</section>

</body>
{% endblock %}

dashboard/templates/dashboard/index.html
{% extends 'registration/base.html' %}
{% load bootstrap3 %}
{% block title %}Index{% endblock %}

{% block content %}

        <header>
            <div class="header-content">
                <div class="header-content-inner">
                    <h1 id="homeHeading">Bem-Vindo ao NOVO CAMINHO</h1>
                    <hr>
                    <p>Você poderá descobrir o que a mídia fala negativamente sobre pessoas, empresas ou quaisquer entidades que quiser!</p>
                    <a href="{% url 'dashboard:login' %}">{% bootstrap_button "Já sou usuário" button_type="submit" button_class="btn btn-primary btn-xl page-scroll" %}</a>
                    <a href="{% url 'dashboard:signup' %}">{% bootstrap_button "Quero cadastrar" button_type="submit" button_class="btn btn-primary btn-xl page-scroll" %}</a>
                    {% if reset_password == 1 %}
                    <br><br>
                    <span>Uma mensagem para redefinir sua senha foi enviada ao seu e-mail.</span>
                    {% endif %}

                </div>
            </div>
        </header>

      {% if error_message %}
      <div class="alert alert-danger" role="alert">
          <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
          <span class="sr-only">Error:</span>
          {{ error_message }}
        </div>
      {% endif %}


{% endblock %}

dashboard/templates/dashboard/services.html
{% extends 'registration/base.html' %}
{% load bootstrap3 %}
{% load static %}
{% block title %} Services {% endblock %}

{% block content %}

    <section class="bg-primary" id="services">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Pesquise as mídias negativas!</h2>
                    <hr class="light">
                    <p class="text-faded">Com o serviço do Novo Caminho você pode saber exatamente o que a mídia anda falando a respeito de alguma pessoa, empresa ou qualquer entidade. Basta um clique para você descobrir quais notícias negativas foram lançadas pela mídia e qual o risco de certa pessoa ou empresa ser perigosa. Comece a pesquisar as notícias agora!</p>
                    <a href="{% url 'dashboard:index' %}" class="page-scroll btn btn-default btn-xl sr-button">Venha para o NOVO CAMINHO!</a>
                </div>
            </div>
        </div>
    </section>

{% endblock %}